<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NDP.Books.Application\NDP.Books.Application.csproj" />
    <ProjectReference Include="..\NDP.Books.Infrastructure\NDP.Books.Infrastructure.csproj" />
  </ItemGroup>

</Project>

