<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NDP.Audits.Application\NDP.Audits.Application.csproj" />
    <ProjectReference Include="..\NDP.Audits.Infrastructure\NDP.Audits.Infrastructure.csproj" />
  </ItemGroup>

</Project>

