<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NDP.Hits.Application\NDP.Hits.Application.csproj" />
    <ProjectReference Include="..\NDP.Hits.Infrastructure\NDP.Hits.Infrastructure.csproj" />
  </ItemGroup>

</Project>

