<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\NDP.Audits.Domain\NDP.Audits.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore"  />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite"  />
  </ItemGroup>

</Project>


