<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\NDP.Identity.Domain\NDP.Identity.Domain.csproj" />
    <ProjectReference Include="..\..\Audits\NDP.Audits.Domain\NDP.Audits.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR"  />
    <PackageReference Include="BCrypt.Net-Next"  />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions"  />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions"  />
  </ItemGroup>

</Project>

